"""add monthly_quota_user

Revision ID: 22bb842e89b1
Revises: aa69c2ab1922
Create Date: 2025-09-11 22:09:45.996165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22bb842e89b1'
down_revision: Union[str, Sequence[str], None] = 'aa69c2ab1922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_quota_user',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('month', 'user_id', name='pk_month_user')
    )
    #op.create_unique_constraint('uq_month_key', 'monthly_quota', ['month', 'api_key_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_month_key', 'monthly_quota', type_='unique')
    op.drop_table('monthly_quota_user')
    # ### end Alembic commands ###
