"""orm mark pk on monthly_quota_user

Revision ID: 30dcc8632ae0
Revises: 22bb842e89b1
Create Date: 2025-09-11 22:41:09.837554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dcc8632ae0'
down_revision: Union[str, Sequence[str], None] = '22bb842e89b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
