"""change primary key for quota

Revision ID: 3cfeac80b2f7
Revises: 993df9f957ca
Create Date: 2025-09-12 21:58:16.267043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfeac80b2f7'
down_revision: Union[str, Sequence[str], None] = '993df9f957ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
       # 1. Primary Key nur auf month droppen
    op.drop_constraint("monthly_quota_user_pkey", "monthly_quota_user", type_="primary")

    # 2. Primary Key auf (user_id, month) setzen
    op.create_primary_key(
        "monthly_quota_user_pkey",
        "monthly_quota_user",
        ["user_id", "month"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("monthly_quota_user_pkey", "monthly_quota_user", type_="primary")
    op.create_primary_key(
        "monthly_quota_user_pkey",
        "monthly_quota_user",
        ["month"],
    )
    # ### end Alembic commands ###
