version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vatify-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vatify}
      POSTGRES_USER: ${POSTGRES_USER:-vatify}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-vatify}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-vatify} -d ${POSTGRES_DB:-vatify}"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: vatify-adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  pgdata:
